### ISSUE TITLE
Zabbix User Parameter?

### ISSUE THREAD

**Issue by DavidGarciaCat** [GPegel/Template-App-Redis#1]
Hello,

What is the Zabbix User Parameter you are using to get these metrics?
Can you copy/paste the content of that file?

Cheers,

**Comment by GPegel** [comment]
Hello,

At first, I'm sorry for this late response.

I don't use UserParameters for this template. There are agents running on my REDIS servers and I imported this template without any problems and it works fine.

May I ask, why you need the UserParameters?

Kind regards

**Comment by DavidGarciaCat** [comment]
Hello,

I didn't realise the item type was `Zabbix trapper`, so when I read `redis[...]` I though about the UserParameters.

That's all,
