### ISSUE TITLE
Where a scripts?

### ISSUE THREAD

**Issue by itJunky** [GPegel/Template-App-Redis#2]
WTF? Why you don't clone any scripts? This template doesn't work without scripts!!!

**Comment by GPegel** [comment]
Sorry, my bad! I thought I uploaded the complete dir. Anyway, I uploaded the script just af few moments ago. Enjoy. If you have questions, just let me know.

**Comment by itJunky** [comment]
Thanks man. We make this world better ;)

**Comment by GPegel** [comment]
Yes we do! I hope it will work. If not, you know where you can find me ;-)
